version: 2
updates:
  - package-ecosystem: gomod
    open-pull-requests-limit: 5
    directory: /
    schedule:
      interval: weekly
    groups:
      go-modules:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    open-pull-requests-limit: 5
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'
